apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loanorginx-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:jbaddam17/loanoriginx-k8s-deployment.git
    targetRevision: HEAD
    path: local
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
