apiVersion: apps/v1
kind: Deployment
metadata:
  name: los-config-service-deployment
  labels:
    app: los-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: los-config-service
  template:
    metadata:
      labels:
        app: los-config-service
    spec:
      containers:
        - name: los-config-service-latest
          image: jaganreddy17/img-repo:los-config-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: los-config-service
  name: los-config-service
spec:
  selector:
    app: los-config-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
