apiVersion: apps/v1
kind: Deployment
metadata:
  name: los-config-service
  labels:
    app: los-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: los-config-service
  template:
    metadata:
      labels:
        app: los-config-service
    spec:
      containers:
        - name: los-config-service-latest
          env:
            - name: ENVIRONMENT
              value: dev
          image: jaganreddy17/los-config-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: los-config-service
  name: los-config-service
spec:
  selector:
    app: los-config-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
